// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.2.0
// Project name: HelloWatch

#ifndef _HELLOWATCH_UI_H
#define _HELLOWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"

#include "../Func/Inc/PageManager.h"

#include "stdio.h"

// SCREEN: ui_HomePage
//void ui_HomePage_screen_init(void);
//void ui_event_HomePage(lv_event_t * e);
//extern lv_obj_t * ui_HomePage;
//extern lv_obj_t * ui_StepCnLabel;
//extern lv_obj_t * ui_HRArc;
//extern lv_obj_t * ui_HRiconLabel;
//void ui_event_BatArc(lv_event_t * e);
//extern lv_obj_t * ui_BatArc;
//extern lv_obj_t * ui_BaticonLabel;
//extern lv_obj_t * ui_BatNumLabel;
//void ui_event_HumiArc(lv_event_t * e);
//extern lv_obj_t * ui_HumiArc;
//extern lv_obj_t * ui_HumiiconLabel;
//void ui_event_TempArc(lv_event_t * e);
//extern lv_obj_t * ui_TempArc;
//extern lv_obj_t * ui_TempiconLabel;
//extern lv_obj_t * ui_StepiconLabel;
//void ui_event_StepNumBar(lv_event_t * e);
//extern lv_obj_t * ui_StepNumBar;
//extern lv_obj_t * ui_TimeHourLabel;
//extern lv_obj_t * ui_TimeColonLabel;
//extern lv_obj_t * ui_TimeMinuteLabel;
//extern lv_obj_t * ui_DayLabel;
//extern lv_obj_t * ui_DateLabel;
//extern lv_obj_t * ui_TempNumLabel;
//extern lv_obj_t * ui_HumiNumLabel;
//extern lv_obj_t * ui_HRNumLabel;
//extern lv_obj_t * ui_StepNumLabel;
//extern lv_obj_t * ui_DropDownPanel;
//extern lv_obj_t * ui_UpBGPanel;
//void ui_event_NFCButton(lv_event_t * e);
//extern lv_obj_t * ui_NFCButton;
//extern lv_obj_t * ui_NFCLabel;
//extern lv_obj_t * ui_BLEButton;
//extern lv_obj_t * ui_BLELabel;
//extern lv_obj_t * ui_PowerButton;
//extern lv_obj_t * ui_PowerLabel;
//extern lv_obj_t * ui_SetButton;
//extern lv_obj_t * ui_SetLabel;
//extern lv_obj_t * ui_LightSlider;
//extern lv_obj_t * ui_LightLabel;
//extern lv_obj_t * ui_DownBGPanel;
//// SCREEN: ui_MenuPage
//void ui_MenuPage_screen_init(void);
//extern lv_obj_t * ui_MenuPage;
//extern lv_obj_t * ui_Label3;
//extern lv_obj_t * ui_ImgButton2;
//// SCREEN: ui_PagePower
//void ui_PagePower_screen_init(void);
//extern lv_obj_t * ui_PagePower;
//extern lv_obj_t * ui_PowerSlider;
//extern lv_obj_t * ui_PowerDownLabel;
//extern lv_obj_t * ui____initial_actions0;

//LV_FONT_DECLARE(ui_font_CuYuan);
LV_FONT_DECLARE(ui_font_Cuyuan20);
//LV_FONT_DECLARE(ui_font_Cuyuan21);
LV_FONT_DECLARE(ui_font_fonticonfont34);
LV_FONT_DECLARE(ui_font_iconfont16);
LV_FONT_DECLARE(ui_font_iconfont24);
LV_FONT_DECLARE(ui_font_iconfont28);
LV_FONT_DECLARE(ui_font_iconfont30);
LV_FONT_DECLARE(ui_font_iconfont32);
LV_FONT_DECLARE(ui_font_Cuyuan18);
LV_FONT_DECLARE(ui_font_Cuyuan24);
LV_FONT_DECLARE(ui_font_Cuyuan30);
LV_FONT_DECLARE(ui_font_Cuyuan38);
LV_FONT_DECLARE(ui_font_Cuyuan48);
LV_FONT_DECLARE(ui_font_Cuyuan80);
LV_FONT_DECLARE(ui_font_Cuyuan100);
LV_FONT_DECLARE(ui_font_iconfont16);
LV_FONT_DECLARE(ui_font_iconfont24);
LV_FONT_DECLARE(ui_font_iconfont25);
LV_FONT_DECLARE(ui_font_iconfont28);
LV_FONT_DECLARE(ui_font_iconfont29);
LV_FONT_DECLARE(ui_font_iconfont30);
LV_FONT_DECLARE(ui_font_iconfont31);
LV_FONT_DECLARE(ui_font_iconfont32);
LV_FONT_DECLARE(ui_font_iconfont33);
LV_FONT_DECLARE(ui_font_iconfont34);
LV_FONT_DECLARE(ui_font_iconfont45);
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
